Ignore typing warning in test file
I was getting:

> tests/test_mixins_repr.py:36: error: Access to generic instance variables via class is ambiguous  [misc]

and I don't care, especially since this is a test file…